from .device import SolaredgeDevice
from .register import HoldingRegister
from pymodbus.client.mixin import ModbusClientMixin as mcm

import logging

logger = logging.getLogger(__name__)


class SolaredgeMeter(SolaredgeDevice):
    def __init__(self, id: int, offset: int = 0):
        super().__init__(id, offset)
        self.registers = {
            "c_manufacturer": HoldingRegister(
                self.base + 0x0,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Manufacturer",
                None,
            ),
            "c_model": HoldingRegister(
                self.base + 0x10, mcm.DATATYPE.STRING, self, 16, "big", "Model", None
            ),
            "c_version": HoldingRegister(
                self.base + 0x20, mcm.DATATYPE.STRING, self, 16, "big", "Version", None
            ),
            "c_serialnumber": HoldingRegister(
                self.base + 0x30,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Serial Number",
                None,
            ),
            "c_deviceaddress": HoldingRegister(
                self.base + 0x40,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "Device Address",
                None,
            ),
            "c_sunspec_did": HoldingRegister(
                self.base + 0x41,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "SunSpec DID",
                None,
            ),
            "b_rated_energy": HoldingRegister(
                self.base + 0x42,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Rated Energy",
                "Wh",
            ),
            "b_max_charge_power": HoldingRegister(
                self.base + 0x44,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Max Charge Power",
                "W",
            ),
            "b_max_discharge_power": HoldingRegister(
                self.base + 0x46,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Max Discharge Power",
                "W",
            ),
            "b_max_charge_peak_power": HoldingRegister(
                self.base + 0x48,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Max Charge Peak Power",
                "W",
            ),
            "b_max_discharge_peak_power": HoldingRegister(
                self.base + 0x4A,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Max Discharge Peak Power",
                "W",
            ),
            "b_average_temp": HoldingRegister(
                self.base + 0x6C,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Average Temperature",
                "°C",
            ),
            "b_max_temp": HoldingRegister(
                self.base + 0x6E,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Max Temperature",
                "°C",
            ),
            "b_instantaneous_voltage": HoldingRegister(
                self.base + 0x70,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Instantaneous Voltage",
                "V",
            ),
            "b_instantaneous_current": HoldingRegister(
                self.base + 0x72,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Instantaneous Current",
                "A",
            ),
            "b_instantaneous_power": HoldingRegister(
                self.base + 0x74,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Instantaneous Power",
                "W",
            ),
            "b_lifetime_export": HoldingRegister(
                self.base + 0x76,
                mcm.DATATYPE.UINT64,
                self,
                4,
                "little",
                "Lifetime Export Energy",
                "Wh",
            ),
            "b_lifetime_import": HoldingRegister(
                self.base + 0x7A,
                mcm.DATATYPE.UINT64,
                self,
                4,
                "little",
                "Lifetime Import Energy",
                "Wh",
            ),
            "b_max_energy": HoldingRegister(
                self.base + 0x7E,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Max Energy",
                "Wh",
            ),
            "b_available_energy": HoldingRegister(
                self.base + 0x80,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "Available Energy",
                "Wh",
            ),
            "b_state_of_health": HoldingRegister(
                self.base + 0x82,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "State of Health",
                "%",
            ),
            "b_state_of_charge": HoldingRegister(
                self.base + 0x84,
                mcm.DATATYPE.FLOAT32,
                self,
                2,
                "little",
                "State of Charge",
                "%",
            ),
            "b_status": HoldingRegister(
                self.base + 0x86, mcm.DATATYPE.UINT32, self, 2, "little", "Status", None
            ),
            "b_status_internal": HoldingRegister(
                self.base + 0x88,
                mcm.DATATYPE.UINT32,
                self,
                2,
                "little",
                "Internal Status",
                None,
            ),
            "b_event_log": HoldingRegister(
                self.base + 0x8A,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "little",
                "Event Log",
                None,
            ),
            "b_event_log_internal": HoldingRegister(
                self.base + 0x92,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "little",
                "Internal Event Log",
                None,
            ),
        }
        self._init_registers()
