from .device import SolaredgeDevice
from .register import HoldingRegister
from pymodbus.client.mixin import ModbusClientMixin as mcm

import logging

logger = logging.getLogger(__name__)


class SolaredgeMeter(SolaredgeDevice):
    def __init__(self, id: int, offset: int = 0):
        super().__init__(id, offset)
        self.registers = {
            "c_manufacturer": HoldingRegister(
                self.base + 0x4,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Manufacturer",
                None,
            ),
            "c_model": HoldingRegister(
                self.base + 0x14, mcm.DATATYPE.STRING, self, 16, "big", "Model", None
            ),
            "c_option": HoldingRegister(
                self.base + 0x24, mcm.DATATYPE.STRING, self, 8, "big", "Option", None
            ),
            "c_version": HoldingRegister(
                self.base + 0x2C, mcm.DATATYPE.STRING, self, 8, "big", "Version", None
            ),
            "c_serialnumber": HoldingRegister(
                self.base + 0x34,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Serial Number",
                None,
            ),
            "c_deviceaddress": HoldingRegister(
                self.base + 0x44,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "Device Address",
                None,
            ),
            "c_sunspec_did": HoldingRegister(
                self.base + 0x45,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "SunSpec DID",
                None,
            ),
            "c_sunspec_length": HoldingRegister(
                self.base + 0x46,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "SunSpec Length",
                None,
            ),
            "m_ac_current": HoldingRegister(
                self.base + 0x47, mcm.DATATYPE.INT16, self, 1, "big", "AC Current", "A"
            ),
            "m_ac_currenta": HoldingRegister(
                self.base + 0x48,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Phase A",
                "A",
            ),
            "m_ac_currentb": HoldingRegister(
                self.base + 0x49,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Phase B",
                "A",
            ),
            "m_ac_currentc": HoldingRegister(
                self.base + 0x4A,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Phase C",
                "A",
            ),
            "m_ac_current_sf": HoldingRegister(
                self.base + 0x4B,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Scale Factor",
                None,
            ),
            "m_ac_voltageab": HoldingRegister(
                self.base + 0x4C,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase AB",
                "V",
            ),
            "m_ac_voltagebc": HoldingRegister(
                self.base + 0x4D,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase BC",
                "V",
            ),
            "m_ac_voltageca": HoldingRegister(
                self.base + 0x4E,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase CA",
                "V",
            ),
            "m_ac_voltagean": HoldingRegister(
                self.base + 0x4F,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase AN",
                "V",
            ),
            "m_ac_voltagebn": HoldingRegister(
                self.base + 0x50,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase BN",
                "V",
            ),
            "m_ac_voltagecn": HoldingRegister(
                self.base + 0x51,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase CN",
                "V",
            ),
            "m_ac_voltage_sf": HoldingRegister(
                self.base + 0x52,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Scale Factor",
                None,
            ),
            "m_ac_frequency": HoldingRegister(
                self.base + 0x53,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Frequency",
                "Hz",
            ),
            "m_ac_frequency_sf": HoldingRegister(
                self.base + 0x54,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Frequency Scale Factor",
                None,
            ),
            "m_ac_power": HoldingRegister(
                self.base + 0x55, mcm.DATATYPE.INT16, self, 1, "big", "AC Power", "W"
            ),
            "m_ac_powera": HoldingRegister(
                self.base + 0x56,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Phase A",
                "W",
            ),
            "m_ac_powerb": HoldingRegister(
                self.base + 0x57,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Phase B",
                "W",
            ),
            "m_ac_powerc": HoldingRegister(
                self.base + 0x58,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Phase C",
                "W",
            ),
            "m_ac_power_sf": HoldingRegister(
                self.base + 0x59,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Scale Factor",
                None,
            ),
            "m_ac_va": HoldingRegister(
                self.base + 0x5A, mcm.DATATYPE.INT16, self, 1, "big", "AC VA", "VA"
            ),
            "m_ac_vaa": HoldingRegister(
                self.base + 0x5B,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VA Phase A",
                "VA",
            ),
            "m_ac_vab": HoldingRegister(
                self.base + 0x5C,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VA Phase B",
                "VA",
            ),
            "m_ac_vac": HoldingRegister(
                self.base + 0x5D,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VA Phase C",
                "VA",
            ),
            "m_ac_va_sf": HoldingRegister(
                self.base + 0x5E,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VA Scale Factor",
                None,
            ),
            "m_ac_var": HoldingRegister(
                self.base + 0x5F, mcm.DATATYPE.INT16, self, 1, "big", "AC VAR", "VAR"
            ),
            "m_ac_vara": HoldingRegister(
                self.base + 0x60,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VAR Phase A",
                "VAR",
            ),
            "m_ac_varb": HoldingRegister(
                self.base + 0x61,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VAR Phase B",
                "VAR",
            ),
            "m_ac_varc": HoldingRegister(
                self.base + 0x62,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VAR Phase C",
                "VAR",
            ),
            "m_ac_var_sf": HoldingRegister(
                self.base + 0x63,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC VAR Scale Factor",
                None,
            ),
            "m_ac_pf": HoldingRegister(
                self.base + 0x64, mcm.DATATYPE.INT16, self, 1, "big", "AC PF", "%"
            ),
            "m_ac_pfa": HoldingRegister(
                self.base + 0x65,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC PF Phase A",
                "%",
            ),
            "m_ac_pfb": HoldingRegister(
                self.base + 0x66,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC PF Phase B",
                "%",
            ),
            "m_ac_pfc": HoldingRegister(
                self.base + 0x67,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC PF Phase C",
                "%",
            ),
            "m_ac_pf_sf": HoldingRegister(
                self.base + 0x68,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC PF Scale Factor",
                None,
            ),
            "m_exported": HoldingRegister(
                self.base + 0x69,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Exported Energy",
                "Wh",
            ),
            "m_exported_a": HoldingRegister(
                self.base + 0x6B,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Exported Energy Phase A",
                "Wh",
            ),
            "m_exported_b": HoldingRegister(
                self.base + 0x6D,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Exported Energy Phase B",
                "Wh",
            ),
            "m_exported_c": HoldingRegister(
                self.base + 0x6F,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Exported Energy Phase C",
                "Wh",
            ),
            "m_imported": HoldingRegister(
                self.base + 0x71,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Imported Energy",
                "Wh",
            ),
            "m_imported_a": HoldingRegister(
                self.base + 0x73,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Imported Energy Phase A",
                "Wh",
            ),
            "m_imported_b": HoldingRegister(
                self.base + 0x75,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Imported Energy Phase B",
                "Wh",
            ),
            "m_imported_c": HoldingRegister(
                self.base + 0x77,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "Total Imported Energy Phase C",
                "Wh",
            ),
            "m_energy_sf": HoldingRegister(
                self.base + 0x79,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "Energy Scale Factor",
                None,
            ),
        }
