from .device import SolaredgeDevice
from .register import HoldingRegister
from pymodbus.client.mixin import ModbusClientMixin as mcm

import logging

logger = logging.getLogger(__name__)


class SolaredgeMeter(SolaredgeDevice):
    def __init__(self, id: int, name: str = "", base: int = 0):
        super().__init__(id, base=base, name=name or f"meter_{id}_{hex(base)}")
        self.registers = {
            "c_manufacturer": HoldingRegister(
                self.base + 0x0,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Manufacturer",
                None,
            ),
            "c_model": HoldingRegister(
                self.base + 0x10,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Model",
                None,
            ),
            "c_option": HoldingRegister(
                self.base + 0x20,
                mcm.DATATYPE.STRING,
                self,
                8,
                "big",
                "Option",
                None,
            ),
            "c_version": HoldingRegister(
                self.base + 0x28,
                mcm.DATATYPE.STRING,
                self,
                8,
                "big",
                "Version",
                None,
            ),
            "c_serialnumber": HoldingRegister(
                self.base + 0x30,
                mcm.DATATYPE.STRING,
                self,
                16,
                "big",
                "Serial Number",
                None,
            ),
            "c_deviceaddress": HoldingRegister(
                self.base + 0x40,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "Device Address",
                None,
            ),
            "c_sunspec_did": HoldingRegister(
                self.base + 0x41,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "SunSpec DID",
                None,
            ),
            "c_sunspec_length": HoldingRegister(
                self.base + 0x42,
                mcm.DATATYPE.UINT16,
                self,
                1,
                "big",
                "SunSpec Length",
                None,
            ),
            "m_ac_current": HoldingRegister(
                self.base + 0x43,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current",
                "A",
            ),
            "m_ac_currenta": HoldingRegister(
                self.base + 0x44,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Phase A",
                "A",
                sf_key="m_ac_current_sf",
            ),
            "m_ac_currentb": HoldingRegister(
                self.base + 0x45,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Phase B",
                "A",
                sf_key="m_ac_current_sf",
            ),
            "m_ac_currentc": HoldingRegister(
                self.base + 0x46,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Phase C",
                "A",
                sf_key="m_ac_current_sf",
            ),
            "m_ac_current_sf": HoldingRegister(
                self.base + 0x47,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Current Scale Factor",
                None,
            ),
            "m_ac_voltage_ln": HoldingRegister(
                self.base + 0x48,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Line-Neutral",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltagean": HoldingRegister(
                self.base + 0x49,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase A-Neutral",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltagebn": HoldingRegister(
                self.base + 0x4A,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase B-Neutral",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltagecn": HoldingRegister(
                self.base + 0x4B,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase C-Neutral",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltage_ll": HoldingRegister(
                self.base + 0x4C,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Line-Line",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltageab": HoldingRegister(
                self.base + 0x4D,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase A-B",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltagebc": HoldingRegister(
                self.base + 0x4E,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase B-C",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltageca": HoldingRegister(
                self.base + 0x4F,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Phase C-A",
                "V",
                sf_key="m_ac_voltage_sf",
            ),
            "m_ac_voltage_sf": HoldingRegister(
                self.base + 0x50,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Voltage Scale Factor",
                None,
            ),
            "m_ac_frequency": HoldingRegister(
                self.base + 0x51,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Frequency",
                "Hz",
                sf_key="m_ac_frequency_sf",
            ),
            "m_ac_frequency_sf": HoldingRegister(
                self.base + 0x52,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Frequency Scale Factor",
                None,
            ),
            "m_ac_power": HoldingRegister(
                self.base + 0x53,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power",
                "W",
                sf_key="m_ac_power_sf",
            ),
            "m_ac_powera": HoldingRegister(
                self.base + 0x54,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Phase A",
                "W",
                sf_key="m_ac_power_sf",
            ),
            "m_ac_powerb": HoldingRegister(
                self.base + 0x55,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Phase B",
                "W",
                sf_key="m_ac_power_sf",
            ),
            "m_ac_powerc": HoldingRegister(
                self.base + 0x56,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Phase C",
                "W",
                sf_key="m_ac_power_sf",
            ),
            "m_ac_power_sf": HoldingRegister(
                self.base + 0x57,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Scale Factor",
                None,
            ),
            "m_ac_va": HoldingRegister(
                self.base + 0x58,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Apparent Power",
                "VA",
                sf_key="m_ac_va_sf",
            ),
            "m_ac_vaa": HoldingRegister(
                self.base + 0x59,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Apparent Power Phase A",
                "VA",
                sf_key="m_ac_va_sf",
            ),
            "m_ac_vab": HoldingRegister(
                self.base + 0x5A,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Apparent Power Phase B",
                "VA",
                sf_key="m_ac_va_sf",
            ),
            "m_ac_vac": HoldingRegister(
                self.base + 0x5B,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Apparent Power Phase C",
                "VA",
                sf_key="m_ac_va_sf",
            ),
            "m_ac_va_sf": HoldingRegister(
                self.base + 0x5C,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Apparent Power Scale Factor",
                None,
            ),
            "m_ac_var": HoldingRegister(
                self.base + 0x5D,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Reactive Power",
                "VAR",
                sf_key="m_ac_var_sf",
            ),
            "m_ac_vara": HoldingRegister(
                self.base + 0x5E,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Reactive Power Phase A",
                "VAR",
                sf_key="m_ac_var_sf",
            ),
            "m_ac_varb": HoldingRegister(
                self.base + 0x5F,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Reactive Power Phase B",
                "VAR",
                sf_key="m_ac_var_sf",
            ),
            "m_ac_varc": HoldingRegister(
                self.base + 0x60,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Reactive Power Phase C",
                "VAR",
                sf_key="m_ac_var_sf",
            ),
            "m_ac_var_sf": HoldingRegister(
                self.base + 0x61,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Reactive Power Scale Factor",
                None,
            ),
            "m_ac_pf": HoldingRegister(
                self.base + 0x62,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Factor",
                "",
                sf_key="m_ac_pf_sf",
            ),
            "m_ac_pfa": HoldingRegister(
                self.base + 0x63,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Factor Phase A",
                "",
                sf_key="m_ac_pf_sf",
            ),
            "m_ac_pfb": HoldingRegister(
                self.base + 0x64,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Factor Phase B",
                "",
                sf_key="m_ac_pf_sf",
            ),
            "m_ac_pfc": HoldingRegister(
                self.base + 0x65,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Factor Phase C",
                "",
                sf_key="m_ac_pf_sf",
            ),
            "m_ac_pf_sf": HoldingRegister(
                self.base + 0x66,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Power Factor Scale Factor",
                None,
            ),
            "m_exported_wh": HoldingRegister(
                self.base + 0x67,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Imported",
                "Wh",
            ),
            "m_exported_wha": HoldingRegister(
                self.base + 0x69,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Imported Phase A",
                "Wh",
            ),
            "m_exported_whb": HoldingRegister(
                self.base + 0x6B,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Imported Phase B",
                "Wh",
            ),
            "m_exported_whc": HoldingRegister(
                self.base + 0x6D,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Imported Phase C",
                "Wh",
            ),
            "m_imported_wh": HoldingRegister(
                self.base + 0x6F,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Exported",
                "Wh",
            ),
            "m_imported_wha": HoldingRegister(
                self.base + 0x71,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Exported Phase A",
                "Wh",
                sf_key="m_wh_sf",
            ),
            "m_imported_whb": HoldingRegister(
                self.base + 0x73,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Exported Phase B",
                "Wh",
                sf_key="m_wh_sf",
            ),
            "m_imported_whc": HoldingRegister(
                self.base + 0x75,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Energy - Exported Phase C",
                "Wh",
                sf_key="m_wh_sf",
            ),
            "m_wh_sf": HoldingRegister(
                self.base + 0x77,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Energy Scale Factor",
                None,
            ),
            "m_vah_exp": HoldingRegister(
                self.base + 0x78,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Exported",
                "VAh",
            ),
            "m_vah_expa": HoldingRegister(
                self.base + 0x7A,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Exported Phase A",
                "VAh",
            ),
            "m_vah_expb": HoldingRegister(
                self.base + 0x7C,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Exported Phase B",
                "VAh",
            ),
            "m_vah_expc": HoldingRegister(
                self.base + 0x7E,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Exported Phase C",
                "VAh",
            ),
            "m_vah_imp": HoldingRegister(
                self.base + 0x80,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Imported",
                "VAh",
            ),
            "m_vah_impa": HoldingRegister(
                self.base + 0x82,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Imported Phase A",
                "VAh",
            ),
            "m_vah_impb": HoldingRegister(
                self.base + 0x84,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Imported Phase B",
                "VAh",
            ),
            "m_vah_impc": HoldingRegister(
                self.base + 0x86,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Apparent Energy - Imported Phase C",
                "VAh",
            ),
            "m_vah_sf": HoldingRegister(
                self.base + 0x88,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Apparent Energy Scale Factor",
                None,
            ),
            "m_varh_imp_q1": HoldingRegister(
                self.base + 0x89,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q1",
                "VArh",
            ),
            "m_varh_imp_q1a": HoldingRegister(
                self.base + 0x8B,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q1 Phase A",
                "VArh",
            ),
            "m_varh_imp_q1b": HoldingRegister(
                self.base + 0x8D,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q1 Phase B",
                "VArh",
            ),
            "m_varh_imp_q1c": HoldingRegister(
                self.base + 0x8F,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q1 Phase C",
                "VArh",
            ),
            "m_varh_imp_q2": HoldingRegister(
                self.base + 0x91,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q2",
                "VArh",
            ),
            "m_varh_imp_q2a": HoldingRegister(
                self.base + 0x93,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q2 Phase A",
                "VArh",
            ),
            "m_varh_imp_q2b": HoldingRegister(
                self.base + 0x95,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q2 Phase B",
                "VArh",
            ),
            "m_varh_imp_q2c": HoldingRegister(
                self.base + 0x97,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Imported Q2 Phase C",
                "VArh",
            ),
            "m_varh_exp_q3": HoldingRegister(
                self.base + 0x99,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q3",
                "VArh",
            ),
            "m_varh_exp_q3a": HoldingRegister(
                self.base + 0x9B,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q3 Phase A",
                "VArh",
            ),
            "m_varh_exp_q3b": HoldingRegister(
                self.base + 0x9D,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q3 Phase B",
                "VArh",
            ),
            "m_varh_exp_q3c": HoldingRegister(
                self.base + 0x9F,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q3 Phase C",
                "VArh",
            ),
            "m_varh_exp_q4": HoldingRegister(
                self.base + 0xA1,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q4",
                "VArh",
            ),
            "m_varh_exp_q4a": HoldingRegister(
                self.base + 0xA3,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q4 Phase A",
                "VArh",
            ),
            "m_varh_exp_q4b": HoldingRegister(
                self.base + 0xA5,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q4 Phase B",
                "VArh",
            ),
            "m_varh_exp_q4c": HoldingRegister(
                self.base + 0xA7,
                mcm.DATATYPE.INT32,
                self,
                2,
                "big",
                "AC Reactive Energy - Exported Q4 Phase C",
                "VArh",
            ),
            "m_varh_sf": HoldingRegister(
                self.base + 0xA9,
                mcm.DATATYPE.INT16,
                self,
                1,
                "big",
                "AC Reactive Energy Scale Factor",
                None,
            ),
        }
        self._init_registers()
